[package]
name = "catalina-instruments"
version = "0.1.0"
edition = "2024"

[dependencies]
catalina-engine = { path = "../catalina-engine" }
heapless = "0.9.2"

[features]
default = []
std = []
alloc = []
